user_token = ""
siyuan_token = ""
api_host = "https://www.yuque.com/api/v2"
last_sync_time = "20211024215817"
assets_replacement = "https://b3logfile.com/siyuan/1609132319768/assets"
[[custom_sync]]
sql = "select * from blocks where hpath like '%Math/%' and type='d'"
yuque-workspace = "clouder0/gaokao"

[[custom_sync]]
sql = "SELECT * FROM blocks WHERE id IN(SELECT parent_id FROM blocks WHERE path LIKE ((SELECT REPLACE(path,'.sy','/%') path FROM blocks WHERE id ='20211023174003-hqvfd8i')) AND length != 0) AND type = 'd'"
yuque-workspace = "clouder0/siyuan"


